repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [ "--branch", "main" ]
      - id: trailing-whitespace
        args: [ "--markdown-linebreak-ext=md" ]
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: Generates table of contents for markdown files
        files: \.md$
        args:
          - "--maxlevel"
          - "4"
          - "--title"
          - "# Table of Contents"
          - "--update-only"
          - "src"
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
          "pydantic==2.5.2",
        ]
        args: ["--install-types", "--non-interactive"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]
