services:

  app:
    image: flashcards-app
    container_name: flashcards-app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8080"
    volumes:
      - .:/app/
    restart: always
