services:

  app:
    image: flashcards-app
    container_name: flashcards-app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - DISPLAY=$DISPLAY
      - USE_X11=1
      - LIBGL_ALWAYS_INDIRECT=1  # https://github.com/XQuartz/XQuartz/issues/144#issuecomment-907511509

    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - .:/app/
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
